### ISSUE TITLE
Cannot load some indicators in newer versions

### ISSUE THREAD

**Issue by vaunus** [anandanand84/technicalindicators#38]
I am seeing issues with a number of the candlestick patterns in newer versions with error
> Cannot read property 'hasPattern' of undefined

For example:
```
let doji = require('technicalindicators').Doji
let values = ...
doji.hasPattern(values)
```

The above will throw the error and I am seeing this across a number of patterns, not just Doji. The last version available on npm that seems stable is 0.2.17.

**Comment by anandanand84** [comment]
Ok with the 0.2.20 version we migrated things to typescript and there are few breaking changes, technically it should be a major bump, since not a lot of people are using I didn't major bump it. If you are using the latest version in npm, your example should be like

```
let doji = require('technicalindicators').doji
let values = ...
doji(values)
```

We need to update this in runkit.

I also pushed a [Playground with code completion](https://anandanand84.github.io/ "Playground") just now, which has code completion which you can used to test instead of the runkit.
